export const SIGN_IN = 'SIGN_IN'

export const SIGN_OUT = 'SIGN_OUT'

export const SUCCESS = "SUCCESS"

export const FAILURE = "FAILURE"

export const USER_INPUT = "USER_INPUT"

export const LOGIN_SUCCESS = "LOGIN_SUCCESS"

export const LOGIN_FAILURE = "LOGIN_FAILURE"

export const ADD_PROFILE = "ADD_PROFILE"

export const REMOVE_PROFILE = "REMOVE_PROFILE"

export const USER_INPUT_CHANGE = "USER_INPUT_CHANGE"

export const USER_INPUT_SUBMIT = "USER_INPUT_SUBMIT"

export const SET_PROFILE_STATS = "SET_PROFILE_STATS"

export const REMOVE_DB_PROFILE = "REMOVE_DB_PROFILE"

export const AUTH_CHECK = "AUTH_CHECK"

export const INCREMENT_BEER = "INCREMENT_BEER"

export const INCREMENT_SELTZER = "INCREMENT_SELTZER"

export const INCREMENT_CRAFT = "INCREMENT_CRAFT"

export const INCREMENT_WINE = "INCREMENT_WINE"

export const INCREMENT_SHOTS = "SHOTS"

export const INCREMENT_COCKTAIL = "COCKTAIL"

export const DECREMENT_BEER = "DECREMENT_BEER"

export const DECREMENT_SELTZER = "DECREMENT_SELTZER"

export const DECREMENT_CRAFT = "DECREMENT_CRAFT"

export const DECREMENT_WINE = "DECREMENT_WINE"

export const DECREMENT_SHOTS = "DECREMENT_SHOTS"

export const DECREMENT_COCKTAIL = "DECREMENT_COCKTAIL"

export const SUBMIT_DRINK = "SUBMIT_DRINK"

export const FRIEND_SEARCH = "FRIEND_SEARCH"

export const PENDING_REQUESTS = "PENDING_REQUESTS"

export const REMOVE_FROM_PENDING = "REMOVE_FROM_PENDING"

export const FOLLOWING = "FOLLOWING"

export const SHOW_FRIEND_STATS = "SHOW_FRIEND_STATS"

export const HIDE_FRIEND_STATS = "HIDE_FRIEND_STATS"

export const TOTAL_FRIENDS = "TOTAL_FRIENDS"

export const FRIEND_CLICK_ON = "FRIEND_CLICK_ON"

export const FRIEND_CLICK_OFF = "FRIEND_CLICK_OFF"

export const LAST_ENTRY = "LAST_ENTRY"

export const FRIENDS_LAST_ENTRY = "FRIENDS_LAST_ENTRY"

export const CUMULATIVE_DRINKS = "CUMULATIVE_DRINKS"