export const SIGN_IN = 'SIGN_IN'

export const SIGN_OUT = 'SIGN_OUT'

export const SUCCESS = "SUCCESS"

export const FAILURE = "FAILURE"

export const USER_INPUT = "USER_INPUT"

export const LOGIN_SUCCESS = "LOGIN_SUCCESS"

export const LOGIN_FAILURE = "LOGIN_FAILURE"

export const ADD_PROFILE = "ADD_PROFILE"

export const REMOVE_PROFILE = "REMOVE_PROFILE"

export const USER_INPUT_CHANGE = "USER_INPUT_CHANGE"

export const USER_INPUT_SUBMIT = "USER_INPUT_SUBMIT"

export const SET_PROFILE_STATS = "SET_PROFILE_STATS"

export const REMOVE_DB_PROFILE = "REMOVE_DB_PROFILE"

export const AUTH_CHECK = "AUTH_CHECK"

export const INCREMENT_BEER = "INCREMENT_BEER"

export const INCREMENT_WINE = "INCREMENT_WINE"

export const INCREMENT_SHOTS = "SHOTS"

export const INCREMENT_COCKTAIL = "COCKTAIL"

export const DECREMENT_BEER = "DECREMENT_BEER"

export const DECREMENT_WINE = "DECREMENT_WINE"

export const DECREMENT_SHOTS = "DECREMENT_SHOTS"

export const DECREMENT_COCKTAIL = "DECREMENT_COCKTAIL"

export const SUBMIT_DRINK = "SUBMIT_DRINK"

export const FRIEND_SEARCH = "FRIEND_SEARCH"
